### ISSUE TITLE
Clearly Document the Advanced Session Resource API Dependency

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/FPGA-Module#7]
This module still needs the API to get a list of resources from a session and open individual connections to each item. 

http://forums.ni.com/t5/NI-Labs-Toolkits/LabVIEW-FPGA-Advanced-Session-Resources/ta-p/3500447

This is also missing a link to LabVIEW 2017. It'd be good to get that fixed or see if the 2016 files happen to work in 17.

**Comment by pollockm** [comment]
Per @a-clucker , the 2016 installer does not work on LV 2017.

**Comment by pollockm** [comment]
If there's a way to make a VI Package out of the files, that would be useful.

**Comment by pollockm** [comment]
Left comments on Barrett's thread asking for 2017.
